[versions]
agp = "8.9.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
room = "2.6.1"
ksp = "2.0.21-1.0.25"
koin = "3.2.0"
glide = "4.16.0"
mockk = "1.13.10"
coretesting = "2.2.0"
coroutines = "1.7.3"
compose-bom = "2024.10.01"
compose-activity = "1.9.3"
compose-ui = "1.7.3"
compose-material3 = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
roomcompiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
roomruntime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room = {group = "androidx.room", name = "room-ktx", version.ref = "room"}
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koincompat = { group = "io.insert-koin", name = "koin-android-compat", version.ref = "koin" }
koinworkmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koinnavigation = { group = "io.insert-koin", name = "koin-androidx-navigation", version.ref = "koin" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
mockk = {group = "io.mockk", name = "mockk", version.ref = "mockk"}
coretesting = { group = "androidx.arch.core", name = "core-testing", version.ref = "coretesting" }
coroutines = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }